client_config_backend: file
client_config:
    client_id: 397506226541-8o5ifp2e40vma8pvalp5prjkskojgjvl.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive 